CREATE VIEW [meta].[v_TablesINFOR] AS 
SELECT [tabinID]
      ,[tabin_SchemaSOURCE]
      ,[tabin_TableNameSOURCE]
      ,[tabin_Active]
      ,[tabin_TableLoadPRIORITY]
      ,[tabin_serv_ClientID]
      ,[tabin_BusinessCompanyNumber]
      ,[tabin_bcnr_BCNRange]
      ,[tabin_TableNameTARGET]
      ,[tabin_TableCommonName]
      ,[tabin_IncrementDays]
      ,[tabin_IncrementColumn]
  FROM [DWH_Staging_DEV].[meta].[TablesINFOR]
